name: CI

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        working-directory: frontend
        run: npm install

      - name: Run tests
        working-directory: frontend
        run: npm test -- --watchAll=false --passWithNoTests

  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: frontend
        run: npm install --save-dev eslint

      - name: Run ESLint
        working-directory: frontend
        run: npm run eslint

  push:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: jayram0407
          password: dckr_pat_yMnbN_zvHHgCx1wWdmy5ljStDh8

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: jayram0407/referme:latest

  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest
    needs: push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: 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

      - name: Update tag in Helm chart
        run: |
          sed -i 's/tag: .*/tag: "latest"/' helm/referme-frontend-chart/values.yaml

      - name: Commit and push changes
        run: |
          git config --global user.email "jayramsharma0402@gmail.com"
          git config --global user.name "Jayram Sharma"
          git add helm/referme-frontend-chart/values.yaml
          git commit -m "Update tag in Helm chart"
          git push

